### ISSUE TITLE
change bot's owner

### ISSUE THREAD

**Issue by rinme** [the-urban-inc/nhentai-discord-bot#29]
how to change owner thing or can i add multi owner?

**Comment by minhducsun2002** [comment]
The bot owner is the individual in possession of the Discord application that the bot user account itself belongs to.
I would recommend hosting the bot with your own account, should you wish to set yourself as the owner.

Multiple owner is not supported right now.

**Comment by minhducsun2002** [comment]
Closing this issue. Feel free to reopen it should you have further questions.
