### ISSUE TITLE
Slash doesn't work and n! prefix

### ISSUE THREAD

**Issue by StrangerGithuber** [the-urban-inc/nhentai-discord-bot#34]
Hello
The code which you shared the prefix n! doesn't work and slash either as if you missed some parts of the code.
I built the code successfully but when using those prefixes then nothing happens.

Plus when using pnpm run start:web then getting the error message which says the Logger is not a constructor.

**Comment by t41y0u** [comment]
Hello, 

The code is working properly, and I have stated in the README that I won't provide any support for self-hosting. 

As for why it didn't work for you, the n! prefix and the web part is implemented in another repo and hosted along side with this repo which only supports slash and buttons. Plus the web part in this repo is still bugged. 

Any further support will not be provided.
