### ISSUE TITLE
Time out bot idiot proofing (asmr function)

### ISSUE THREAD

**Issue by newusernamed** [the-urban-inc/nhentai-discord-bot#35]
/join cmd not working
## Expected Behavior

bot should join
## Current Behavior

error message (Failed to join voice channel within 20 seconds, please try again later!)
## Possible Solution

Cmd to reset the whole bot/ bot detects it has been time out and reset it audio

## Steps to Reproduce

1.time out bot while it is in voice channel
2.once timeout is over add attempt do /join cmd
3.no longer works
4.

## Context (Environment)

bot asmr function no longer works

Idiot proofing

Bot does not manage to deal with timeout while in voice channel

**Comment by t41y0u** [comment]
Fixed
